
server:
  port: 9998
spring:
  application:
    name: blog-producer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.11.8:1521:orcl
    password: xtkj123
    username: scott
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/xtkj/mapper/*.xml
  type-aliases-package: com.xtkj.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/