

server:
  port: 19998
spring:
  application:
    name: blog-producer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.11.8:1521:orcl
    password: xtkj123
    username: scott
  zipkin:
    base-url: http://xtkj1.com:9411
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:com/xtkj/mapper/*.xml
  type-aliases-package: com.xtkj.pojo
eureka:
  instance:
    instance-id: producer-19998
    ip-address: true
  client:
    service-url:
      defaultZone: http://xtkj1.com:9999/eureka/,http://xtkj2.com:19999/eureka/
info:
  app:
    name: superMan
    company: 讯腾科技
  build:
    artifactId: spring-blog-producer-19998
    version : 0.0.1-SNAPSHOT