spring:
  profiles:
    active:
    - dev
---
server:
  port: 19999
spring:
  profiles: dev
  application:
    name: eureka-register-19999-dev
  zipkin:
    base-url: http://xtkj1.com:9411
eureka:
  instance:
    hostname: xtkj2.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://xtkj1.com:9999/eureka/
      #defaultZone: http://localhost:9999/eureka/
---
server:
  port: 9999
spring:
  profiles: test
  application:
    name: eureka-register-9999-test
eureka:
  instance:
    hostname: xtkj1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://xtkj2.com:19999/eureka/