
server:
  port: 19999
spring:
  application:
    name: eureka-register-19999
eureka:
  instance:
    hostname: xtkj2.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://xtkj1.com:9999/eureka/
      #defaultZone: http://localhost:9999/eureka/