
server:
  port: 9997
eureka:
  client:
    service-url:
      defaultZone: http://xtkj1.com:9999/eureka/,http://xtkj2.com:19999/eureka/
spring:
  application:
    name: consumer-blog
feign:
  hystrix:
    enabled: true
  client: #设置 超时配置
    config:
      default:
        connectTimeout: 7000
        readTimeout: 7000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000