server:
  port: 9999
spring:
  application:
    name: eureka-register
eureka:
  instance:
    hostname: xtkj1.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://xtkj2.com:19999/eureka/ #,http://xtkj3.com:29999